# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('penalty', models.IntegerField(default=0)),
                ('date_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parking_Lot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('photo', models.CharField(default='files/pk_images/default.png', max_length=255)),
                ('max_places', models.IntegerField(default=10)),
                ('rating', models.FloatField(default=0)),
                ('open_hour', models.IntegerField(default=7)),
                ('close_hour', models.IntegerField(default=18)),
                ('price', models.IntegerField(default=10)),
                ('info', models.TextField(null=True)),
                ('lat', models.FloatField()),
                ('longt', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Rated',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('mat', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='rated',
            name='mat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.User'),
        ),
        migrations.AddField(
            model_name='rated',
            name='parking_lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.Parking_Lot'),
        ),
        migrations.AddField(
            model_name='booking',
            name='mat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.User'),
        ),
        migrations.AddField(
            model_name='booking',
            name='parking_lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.Parking_Lot'),
        ),
    ]
